[package]
name = "rust_asio"
version = "0.4.0"
authors = ["Haruhiko Uchida <harre.orz@gmail.com>"]
description = "Asynchronous I/O library"
documentation = "http://harre-orz.github.io/rust_asio/asyncio/"
repository = "https://github.com/harre-orz/rust_asio.git"
keywords = ["asyncio", "asynchronous", "network", "socket"]
license = "MIT"

[lib]
name = "asyncio"

[dependencies]
libc = "^0.2"
errno = "^0.1"
thread-id = "^2.0"
lazy_static = "^0.2"
time = "^0.1"
context = { version = "^1.0", optional = true }
termios = { version = "^0.2", optional = true }

[features]
default = ["context"]
