[package]
name = "rust_asio"
version = "0.4.0"
authors = ["Haruhiko Uchida <harre.orz@gmail.com>"]
description = "Asynchronous I/O library"
documentation = "http://harre-orz.github.io/rust_asio/asio/"
repository = "https://github.com/harre-orz/rust_asio.git"
keywords = ["async", "asynchronous", "network", "socket"]
license = "MIT"

[lib]
name = "asyncio"

[dependencies]
libc = "^0.2"
time = "^0.1"
context = "^1.0"

[features]
asio_no_epoll_reactor = []
#asio_no_kqueue_reactor = []
#asio_no_poll_reactor = []
asio_no_signal_set = []
