[package]
name = "rust_asio"
version = "0.1.2"
authors = ["Haruhiko Uchida <harre.orz@gmail.com>"]
description = "Asynchronous I/O library"
documentation = "http://harre-orz.github.io/rust_asio/asio/"
repository = "https://github.com/harre-orz/rust_asio.git"
keywords = ["async", "asynchronous", "network", "socket"]
license = "MIT"

[lib]
name = "asio"

[dependencies]
libc = "^0.2"
time = "^0.1"

[features]
# cargo doc --features developer
developer = []
